version: 0.0
os: linux

files:
  - source: ./httpd
    destination: /usr/sbin
  - source: ./httpd.service
    destination: /usr/lib/systemd/system
  - source: ./assets.zip
    destination: /srv

hoooks:
  BeforeInstall:
    - location: BeforeInstall.sh
      timeout: 30
  AfterInstall:
    - location: AfterInstall.sh
      timeout: 30
  ApplicationStop:
    - location: ApplicationStop.sh
      timeout: 30
  ApplicationStart:
    - location: ApplicationStart.sh
      timeout: 30
  ValidateService:
    - location: ValidateService.sh
      timeout: 30