# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: travmatth/amazonlinux-golang-dev

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    environment:
      TEST_RESULTS: /tmp/test-results
      COVERAGE_RESULTS: /tmp/test-coverage
    working_directory: /go/src/github.com/Travmatth/faas
    steps: # steps that compromise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Download dependencies
          command: make get
      - run:
          name: Perform linting, vetting, testing
          command: make check
      - run:
          name: Generate code coverage.html
          command: |
              make coverage.html
              mv coverage.html /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
      - store_test_results: # upload test results for display in Test Summary
          path: tmp/test-results
workflows:
  version: 2
  build-workflow:
    jobs:
      - build