env: PRODUCTION
net:
  static: /srv/web/www/static
  ip: 0.0.0.0
  port: :80
  liveness: 10
timeout:
  read: 5
  write: 5
  stop: 5
  idle: 5
aws:
  region: us-west-1
  dynamodb:
    endpoint: http://localhost:8000
    pagination_limit: 5
    table:
      quote: "qaas-quote-table"
      author: "qaas-author-table"
      topic: "qaas-topic-table"